tags = ["Hakos Baelz"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLcPAszg2ItaGAkxKIUiTTtgekfmgMmmEQ"

[[videos]]
url = "https://www.youtube.com/watch?v=na6bysYNuS0&list=PLcPAszg2ItaGAkxKIUiTTtgekfmgMmmEQ&index=3"
tags = ["オリジナル"]
