tags = ["IRyS"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLpBqtLy3mHw2Wlox1cPU2-WGM5VmMYR8m"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLpBqtLy3mHw07nf_D8u-g6a3_MdLWVdIc"
tags = ["オリジナル"]
