tags = ["Mori Calliope"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLB8Nt5W7hnKA_pG2qljWbgVmJPobrLTm4"

[[videos]]
url = "https://www.youtube.com/watch?v=zbgWUK_tidI"
tags = ["Mori Calliope", "Takanashi Kiara", "Ninomae Ina'nis", "Gawr Gura", "Watson Amelia"]

[[videos]]
url = "https://www.youtube.com/watch?v=VNU2BDdgPZ8"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=3RxlzJWWzdY"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=6ydgEipkUEU"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=-AuQZrUHjhg"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=VYu3PvRPZR8"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=h-LOlueKCtk"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=_M-6lkoi6L4"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=5y3xh8gs24c"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=vz7JIBvAFqM"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=PluDFsVo3z0"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=5HWCMh1ZmzE"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=aetXqd9B8WE"
tags = ["Gawr Gura", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=HSC3BheJuhU"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=tzOXIHGfVFc"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=YOuNKm4ApZY"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=DOzpsXZS-j0"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=8bc1GW-zsPY"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=M85xU-tbQ6c"
tags = ["オリジナル"]
