tags = ["Nanashi Mumei"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PL6IyOjey3U8WiUwXw-1AIDv99qMB9otjp"

[[videos]]
url = "https://www.youtube.com/watch?v=Py21QCndbxc"
tags = ["オリジナル"]
