tags = ["Ninomae Ina'nis"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLQZecHYc3j2plhVMu0squPpD4XRoQmX-y"

[[videos]]
url = "https://www.youtube.com/watch?v=8ZdLXELdF9Q"
tags = ["オリジナル"]
