[project]
title = "template"
description = "YouTube video playlist"
origin = "https://holomuses.github.io"
ogimage = "/favicon.png"
splashimage = "/favicon.png"
color = "#74CFE2"

[[playlist]]
id = "PL1NeGg1woXqkTks79_kSoxBrEKloB9SrI"
tags = ["official"]

# ときのそら
[[playlist]] # https://www.youtube.com/playlist?list=PL_0A0t0-Y0AMGFPCuKDZ3o8PMVpKcNvOQ
id = "PL_0A0t0-Y0AMGFPCuKDZ3o8PMVpKcNvOQ"
tags = ["ときのそら"]
# AZKi
[[playlist]] # https://www.youtube.com/playlist?list=PLpt61bADOMwXIZpLr09sCNeocN7CXjcoS
id = "PLpt61bADOMwXIZpLr09sCNeocN7CXjcoS"
tags = ["AZKi"]
# ロボ子さん
[[video]] # https://www.youtube.com/watch?v=yfEUPlRuPac
id = "yfEUPlRuPac"
tags = ["ロボ子さん", "友人A"]
[[video]] # https://www.youtube.com/watch?v=ZshLem1OV7k
id = "ZshLem1OV7k"
tags = ["ロボ子さん"]
[[video]] # https://www.youtube.com/watch?v=RJwpJIe5FmY
id = "RJwpJIe5FmY"
tags = ["ロボ子さん"]
[[video]] # https://www.youtube.com/watch?v=sJZoMJfIpmA
id = "sJZoMJfIpmA"
tags = ["ロボ子さん"]
[[video]] # https://www.youtube.com/watch?v=ydprczRfM48
id = "ydprczRfM48"
tags = ["ロボ子さん"]
[[video]] # https://www.youtube.com/watch?v=yIvcKk4vZ7Y
id = "yIvcKk4vZ7Y"
tags = ["ロボ子さん", "さくらみこ", "大神ミオ"]
[[video]] # https://www.youtube.com/watch?v=c25iBKPN6w4
id = "c25iBKPN6w4"
tags = ["ロボ子さん"]
[[video]] # https://www.youtube.com/watch?v=K7FqZJS-ZwA
id = "K7FqZJS-ZwA"
tags = ["ロボ子さん", "ときのそら"]
[[video]] # https://www.youtube.com/watch?v=fY1CQ5kSRxY
id = "fY1CQ5kSRxY"
tags = ["ロボ子さん"]
[[video]] # https://www.youtube.com/watch?v=e_EqIA6ZWqs
id = "e_EqIA6ZWqs"
tags = ["ロボ子さん"]
[[video]] # https://www.youtube.com/watch?v=QP-caiSnm2Q
id = "QP-caiSnm2Q"
tags = ["ロボ子さん", "アキ・ローゼンタール"]
# さくらみこ
[[playlist]] # https://www.youtube.com/playlist?list=PLMF8NocLqJtubiccXUm9SCZ79dDPSLq2B
id = "PLMF8NocLqJtubiccXUm9SCZ79dDPSLq2B"
tags = ["さくらみこ"]
[[playlist]] # https://www.youtube.com/playlist?list=PLMF8NocLqJttJCIiUCkNXx6jW4dAYfz5G
id = "PLMF8NocLqJttJCIiUCkNXx6jW4dAYfz5G"
tags = ["さくらみこ", "オリジナル"]
# 白上フブキ
[[playlist]] # https://www.youtube.com/playlist?list=PL7LdRPp7xCkOwyOEKkE5YNC1_pGCTU2Id
id = "PL7LdRPp7xCkOwyOEKkE5YNC1_pGCTU2Id"
tags = ["白上フブキ"]
# 夏色まつり
[[playlist]] # https://www.youtube.com/playlist?list=PL6sZ3uYmeG1vGZVLNlWdJkm3W0R86y_Qa
id = "PL6sZ3uYmeG1vGZVLNlWdJkm3W0R86y_Qa"
tags = ["夏色まつり"]
# 夜空メル
[[playlist]] # https://www.youtube.com/playlist?list=PL43udV6iXTkCwnaFSjm3IAtggd7f12onJ
id = "PL43udV6iXTkCwnaFSjm3IAtggd7f12onJ"
tags = ["夜空メル"]
# 赤井はあと
[[playlist]] # https://www.youtube.com/playlist?list=PLQoA24ikdy_kFurrcDRRJufTwHo_Kv6ew
id = "PLQoA24ikdy_kFurrcDRRJufTwHo_Kv6ew"
tags = ["赤井はあと"]
# アキ・ローゼンタール
[[playlist]] # https://www.youtube.com/playlist?list=PLYt9gyZFZDj_e7p0saJXMghPsjmBMwyiO
id = "PLYt9gyZFZDj_e7p0saJXMghPsjmBMwyiO"
tags = ["アキ・ローゼンタール"]
# 湊あくあ
[[playlist]] # https://www.youtube.com/playlist?list=PLUp1t9SPBl6r4nqsQBg7HH7fPX2l9AGQk
id = "PLUp1t9SPBl6r4nqsQBg7HH7fPX2l9AGQk"
tags = ["湊あくあ"]
# 癒月ちょこ
[[playlist]] # https://www.youtube.com/playlist?list=PLbk25bH74T5ZgCqaphR7q_dQ8Ja65Z4r_
id = "PLbk25bH74T5ZgCqaphR7q_dQ8Ja65Z4r_"
tags = ["癒月ちょこ"]
# 百鬼あやめ
[[playlist]] # https://www.youtube.com/playlist?list=PL7EFb7T-o_1O4fE4frYhWI4toIh8q5LWH
id = "PL7EFb7T-o_1O4fE4frYhWI4toIh8q5LWH"
tags = ["百鬼あやめ"]
# 紫咲シオン
[[playlist]] # https://www.youtube.com/playlist?list=PLzYaEBSRCCt5kgnBdQkLM7yDDZt2_NIZG
id = "PLzYaEBSRCCt5kgnBdQkLM7yDDZt2_NIZG"
tags = ["紫咲シオン"]
# 大空スバル
[[playlist]] # https://www.youtube.com/playlist?list=PLOLvMgy3Jf3FVLGFJ4HooifOvd3UIQ1eJ
id = "PLOLvMgy3Jf3FVLGFJ4HooifOvd3UIQ1eJ"
tags = ["大空スバル"]
# 大神ミオ
[[playlist]] # https://www.youtube.com/playlist?list=PLMUtkfkYDjAFJlZeDBNLAlrKjfue2DRRu
id = "PLMUtkfkYDjAFJlZeDBNLAlrKjfue2DRRu"
tags = ["大神ミオ"]
# 猫又おかゆ
[[playlist]] # https://www.youtube.com/playlist?list=PL3y-e0n6k6gDoG3mViEOESGV1WhY8aCrR
id = "PL3y-e0n6k6gDoG3mViEOESGV1WhY8aCrR"
tags = ["猫又おかゆ"]
# 戌神ころね
[[video]] # https://www.youtube.com/watch?v=nks1I1sY53I
id = "nks1I1sY53I"
tags = ["戌神ころね", "オリジナル"]
[[video]] # https://www.youtube.com/watch?v=OGYu6Kj3bL0
id = "OGYu6Kj3bL0"
tags = ["戌神ころね"]
[[video]] # https://www.youtube.com/watch?v=saizawXi4i0
id = "saizawXi4i0"
tags = ["戌神ころね"]
[[video]] # https://www.youtube.com/watch?v=G49bAinM6Lc
id = "G49bAinM6Lc"
tags = ["戌神ころね"]
[[video]] # https://www.youtube.com/watch?v=MiuFIzr8bR0
id = "MiuFIzr8bR0"
tags = ["戌神ころね"]
# 不知火フレア
[[playlist]] # https://www.youtube.com/playlist?list=PLBoFNGFmekcMIhlW5Z-umsS3VPnQx7tI8
id = "PLBoFNGFmekcMIhlW5Z-umsS3VPnQx7tI8"
tags = ["不知火フレア"]
# 宝鐘マリン
[[playlist]] # https://www.youtube.com/playlist?list=PLKo9UD3uKyyFUSwUDM5hCTB4fEvZqYs0P
id = "PLKo9UD3uKyyFUSwUDM5hCTB4fEvZqYs0P"
tags = ["宝鐘マリン"]
# 兎田ぺこら
[[playlist]] # https://www.youtube.com/playlist?list=PL9jli3ZqRhJD13ORC2CUTEYnjeZt9KMPb
id = "PL9jli3ZqRhJD13ORC2CUTEYnjeZt9KMPb"
tags = ["兎田ぺこら"]
# 潤羽るしあ
[[playlist]] # https://www.youtube.com/playlist?list=PL_i2uYKhN9y3qOFj4177ZsINvyS_KUDgb
id = "PL_i2uYKhN9y3qOFj4177ZsINvyS_KUDgb"
tags = ["潤羽るしあ"]
# 星街すいせい
[[playlist]] # https://www.youtube.com/playlist?list=PLAo9RlHR2tDZwddeEyp9nTfpaFB58DrXd
id = "PLAo9RlHR2tDZwddeEyp9nTfpaFB58DrXd"
tags = ["星街すいせい", "オリジナル"]
[[playlist]] # https://www.youtube.com/playlist?list=PLAo9RlHR2tDakgakxbOxT9dAZD0rpwvXQ
id = "PLAo9RlHR2tDakgakxbOxT9dAZD0rpwvXQ"
tags = ["星街すいせい"]
# 天音かなた
[[playlist]] # https://www.youtube.com/playlist?list=PLNvxSJodVoAu5ABQjfuPGnzqkRMLtN0y2
id = "PLNvxSJodVoAu5ABQjfuPGnzqkRMLtN0y2"
tags = ["天音かなた"]
# 桐生ココ
[[playlist]] # https://www.youtube.com/playlist?list=PLw58RgSzDmjocRKHICR26CaiEAmbA6Jlk
id = "PLw58RgSzDmjocRKHICR26CaiEAmbA6Jlk"
tags = ["桐生ココ"]
# 角巻わため
[[playlist]] # https://www.youtube.com/playlist?list=PLZ34fLWik_iAP2AdGLOHthUhAJTrEXqGb
id = "PLZ34fLWik_iAP2AdGLOHthUhAJTrEXqGb"
tags = ["角巻わため"]
# 常闇トワ
[[playlist]] # https://www.youtube.com/playlist?list=PLIHyIgRAWkUz3MAUPbTg9XcuP_rzDJ1bk
id = "PLIHyIgRAWkUz3MAUPbTg9XcuP_rzDJ1bk"
tags = ["常闇トワ"]
# 雪花ラミィ
[[playlist]] # https://www.youtube.com/playlist?list=PL7Mw3OdFU891DfLqncG9cbkwH80lHFZEl
id = "PL7Mw3OdFU891DfLqncG9cbkwH80lHFZEl"
tags = ["雪花ラミィ"]
# 桃鈴ねね
[[playlist]] # https://www.youtube.com/playlist?list=PLet0wKVboCzEMtX-hZQn1obu40HWVKn7q
id = "PLet0wKVboCzEMtX-hZQn1obu40HWVKn7q"
tags = ["桃鈴ねね"]
[[playlist]] # https://www.youtube.com/playlist?list=PLet0wKVboCzF7QGobE077uQ6HogY8abWM
id = "PLet0wKVboCzF7QGobE077uQ6HogY8abWM"
tags = ["桃鈴ねね", "オリジナル"]
# 尾丸ポルカ
[[playlist]] # https://www.youtube.com/playlist?list=PLWGY2acU-ZeTnH4EvPHYEcqCUx145dDUP
id = "PLWGY2acU-ZeTnH4EvPHYEcqCUx145dDUP"
tags = ["尾丸ポルカ"]
# Ayunda Risu
[[playlist]] # https://www.youtube.com/playlist?list=PLHeIKIUgnbJBzW9cvaqSG6P9_NvXldgCH
id = "PLHeIKIUgnbJBzW9cvaqSG6P9_NvXldgCH"
tags = ["Ayunda Risu"]
# Moona Hoshinova
[[playlist]] # https://www.youtube.com/playlist?list=PLdcktSYecSKfeQ7p5CrVO4avrmLzSL8mt
id = "PLdcktSYecSKfeQ7p5CrVO4avrmLzSL8mt"
tags = ["Moona Hoshinova"]
# Airani Iofifteen
[[playlist]] # https://www.youtube.com/playlist?list=PL0OWyC-pOgQnQ1POfg1fOiXffUPE-b3sR
id = "PL0OWyC-pOgQnQ1POfg1fOiXffUPE-b3sR"
tags = ["Airani Iofifteen"]
# Anya Melfissa
[[video]] # https://www.youtube.com/watch?v=ZmM5OgXXVA4
id = "ZmM5OgXXVA4"
tags = ["Anya Melfissa"]
# Pavolia Reine
[[playlist]] # https://www.youtube.com/playlist?list=PLrALGrrF-6IVnnurSv7Nxdxpo5zJmmjnC
id = "PLrALGrrF-6IVnnurSv7Nxdxpo5zJmmjnC"
tags = ["Pavolia Reine"]
# 森美声
[[playlist]] # https://www.youtube.com/playlist?list=PLB8Nt5W7hnKA_pG2qljWbgVmJPobrLTm4
id = "PLB8Nt5W7hnKA_pG2qljWbgVmJPobrLTm4"
tags = ["森美声"]
# 小鳥遊キアラ
[[playlist]] # https://www.youtube.com/playlist?list=PLsAbCDORf2yRA9TvFeQkVXnSHdghrfNuH
id = "PLsAbCDORf2yRA9TvFeQkVXnSHdghrfNuH"
tags = ["小鳥遊キアラ"]
# 一伊那尓栖
[[video]] # https://www.youtube.com/watch?v=8ZdLXELdF9Q
id = "8ZdLXELdF9Q"
tags = ["一伊那尓栖", "オリジナル"]
# がうるぐら
[[video]] # https://www.youtube.com/watch?v=WGgEFoI9MhE
id = "WGgEFoI9MhE"
tags = ["がうるぐら", "オリジナル"]
# IRyS
[[playlist]] # https://www.youtube.com/playlist?list=PLpBqtLy3mHw2Wlox1cPU2-WGM5VmMYR8m
id = "PLpBqtLy3mHw2Wlox1cPU2-WGM5VmMYR8m"
tags = ["IRyS"]
[[playlist]] # https://www.youtube.com/playlist?list=PLpBqtLy3mHw07nf_D8u-g6a3_MdLWVdIc
id = "PLpBqtLy3mHw07nf_D8u-g6a3_MdLWVdIc"
tags = ["IRyS", "オリジナル"]

# [[video]]
# hololive - 過去の大型ライブの映像セレクション(非公開)
# id = "GIZPAJHW5bk"
# tags = ["official", "ライブ"]

# https://www.hololive.tv/terms
# 音楽利用に関するガイドラインの対象外となる楽曲について
# hololive IDOL PROJECT／キラメキライダー☆
[[ignore]]
id = "0o3VrBLh8jI"
[[ignore]]
id = "rDSIUPkuM7U"
