[project]
title = "template"
description = "YouTube video playlist"
origin = "https://holomuses.github.io"
ogimage = "/favicon.png"
splashimage = "/favicon.png"
color = "#74CFE2"

[[playlist]]
id = "PL1NeGg1woXqkTks79_kSoxBrEKloB9SrI"
tags = ["official"]

# ときのそら
[[playlist]] # https://www.youtube.com/playlist?list=PL_0A0t0-Y0AMGFPCuKDZ3o8PMVpKcNvOQ
id = "PL_0A0t0-Y0AMGFPCuKDZ3o8PMVpKcNvOQ"
tags = ["ときのそら"]
# AZKi
[[playlist]] # https://www.youtube.com/playlist?list=PLpt61bADOMwXIZpLr09sCNeocN7CXjcoS
id = "PLpt61bADOMwXIZpLr09sCNeocN7CXjcoS"
tags = ["AZKi"]
# さくらみこ
[[playlist]] # https://www.youtube.com/playlist?list=PLMF8NocLqJtubiccXUm9SCZ79dDPSLq2B
id = "PLMF8NocLqJtubiccXUm9SCZ79dDPSLq2B"
tags = ["さくらみこ"]
[[playlist]] # https://www.youtube.com/playlist?list=PLMF8NocLqJttJCIiUCkNXx6jW4dAYfz5G
id = "PLMF8NocLqJttJCIiUCkNXx6jW4dAYfz5G"
tags = ["さくらみこ", "オリジナル"]
# 白上フブキ
[[playlist]] # https://www.youtube.com/playlist?list=PL7LdRPp7xCkOwyOEKkE5YNC1_pGCTU2Id
id = "PL7LdRPp7xCkOwyOEKkE5YNC1_pGCTU2Id"
tags = ["白上フブキ"]
# 夏色まつり
[[playlist]] # https://www.youtube.com/playlist?list=PL6sZ3uYmeG1vGZVLNlWdJkm3W0R86y_Qa
id = "PL6sZ3uYmeG1vGZVLNlWdJkm3W0R86y_Qa"
tags = ["夏色まつり"]
# 夜空メル
[[playlist]] # https://www.youtube.com/playlist?list=PL43udV6iXTkCwnaFSjm3IAtggd7f12onJ
id = "PL43udV6iXTkCwnaFSjm3IAtggd7f12onJ"
tags = ["夜空メル"]

# 星街すいせい
[[playlist]] # https://www.youtube.com/playlist?list=PLAo9RlHR2tDZwddeEyp9nTfpaFB58DrXd
id = "PLAo9RlHR2tDZwddeEyp9nTfpaFB58DrXd"
tags = ["星街すいせい", "オリジナル"]
[[playlist]] # https://www.youtube.com/playlist?list=PLAo9RlHR2tDakgakxbOxT9dAZD0rpwvXQ
id = "PLAo9RlHR2tDakgakxbOxT9dAZD0rpwvXQ"
tags = ["星街すいせい"]

# 猫又おかゆ
[[playlist]] # https://www.youtube.com/playlist?list=PL3y-e0n6k6gDoG3mViEOESGV1WhY8aCrR
id = "PL3y-e0n6k6gDoG3mViEOESGV1WhY8aCrR"
tags = ["猫又おかゆ"]

# [[video]]
# hololive - 過去の大型ライブの映像セレクション(非公開)
# id = "GIZPAJHW5bk"
# tags = ["official", "ライブ"]

# https://www.hololive.tv/terms
# 音楽利用に関するガイドラインの対象外となる楽曲について
# hololive IDOL PROJECT／キラメキライダー☆
[[ignore]]
id = "0o3VrBLh8jI"
[[ignore]]
id = "rDSIUPkuM7U"
