tags = ["ときのそら"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PL_0A0t0-Y0AMGFPCuKDZ3o8PMVpKcNvOQ"

[[videos]]
url = "https://www.youtube.com/watch?v=tiTnyZ5QLao"
tags = ["AZKi", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=rfONeeXgdCA"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=rbd-m8r5Ujs"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=0XW7d83XI_s"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=G9SWOk2J6aw"
tags = ["さくらみこ", "夜空メル", "ロボ子さん", "大空スバル", "AZKi"]
