tags = ["アキ・ローゼンタール"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLYt9gyZFZDj_e7p0saJXMghPsjmBMwyiO"

[[videos]]
url = "https://www.youtube.com/watch?v=Ii7rtNaGlls"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=eN--w_NA6hs"
tags = ["オリジナル"]
