tags = ["天音かなた"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLNvxSJodVoAu5ABQjfuPGnzqkRMLtN0y2"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLNvxSJodVoAuAqJxsnbT07LeETTwLpXfx"
tags = ["オリジナル"]
