tags = ["博衣こより"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLCxKJRIVDrYHVk6OfBsuGwIujL63ooOQV"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLCxKJRIVDrYFg33j7wh8HIDXD2TLQu_1C"


[[videos]]
url = "https://www.youtube.com/watch?v=nCyKjz-ie3c"
tags = ["ラプラス・ダークネス", "鷹嶺ルイ", "博衣こより", "沙花叉クロヱ", "風真いろは"]
