tags = ["宝鐘マリン"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLKo9UD3uKyyFUSwUDM5hCTB4fEvZqYs0P"

[[videos]]
url = "https://www.youtube.com/watch?v=e7VK3pne8N4"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=_VIeV_LZXHM"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=u_hUpHUTJwQ"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=vV-5W7SFHDc"
tags = ["オリジナル"]
