tags = ["戌神ころね"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLI3I4eCwIlMhCknbIPWKu9ZM60t0_WiAP"
tags = ["戌神ころね", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=N_eK0ujrhmY"
tags = ["宝鐘マリン", "白銀ノエル", "雪花ラミィ"]

[[videos]]
url = "https://www.youtube.com/watch?v=OGYu6Kj3bL0"

[[videos]]
url = "https://www.youtube.com/watch?v=saizawXi4i0"

[[videos]]
url = "https://www.youtube.com/watch?v=G49bAinM6Lc"

[[videos]]
url = "https://www.youtube.com/watch?v=MiuFIzr8bR0"
tags = ["猫又おかゆ"]

[[videos]]
url = "https://www.youtube.com/watch?v=qgeuRSawFaw"

[[videos]]
url = "https://www.youtube.com/watch?v=7jk8e94Cr7U"

[[videos]]
url = "https://www.youtube.com/watch?v=pkWFpUijuMc"
