tags = ["風真いろは"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLUfQ3xz0-Jen7EoEDeZAkl5yVuBdtw-Wl"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLUfQ3xz0-JemBHsJIHPvt0ZTb7YpuwzYm"
