tags = ["ラプラス・ダークネス"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PL-ksV7rAwJHWfgsi38uZEsWpnY128WwBC"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PL-ksV7rAwJHVHphjemOnR07QV9vQi5OY6"
