tags = ["湊あくあ"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLUp1t9SPBl6rKXX4uAYsmEZyBlGwKE6Tl"
tags = ["オリジナル"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLUp1t9SPBl6r4nqsQBg7HH7fPX2l9AGQk"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLUp1t9SPBl6qrPT_W79HOeR6_n-hWsAbk"

[[videos]]
url = "https://www.youtube.com/watch?v=m1mbRCgWO90"
tags = ["白上フブキ"]

[[videos]]
url = "https://www.youtube.com/watch?v=j7pM4M9tO70"
tags = ["紫咲シオン"]

[[videos]]
url = "https://www.youtube.com/watch?v=MKEb-Ox1KEw"
tags = ["宝鐘マリン", "Gawr Gura", "Ninomae Ina'nis", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=6Wbto57VKWk"
tags = ["白上フブキ", "大神ミオ", "宝鐘マリン", "潤羽るしあ", "天音かなた"]

[[videos]]
url = "https://www.youtube.com/watch?v=E6LWLQjgynE"
tags = ["天音かなた"]

[[videos]]
url = "https://www.youtube.com/watch?v=XpgSrULHibg"
tags = ["Startend", "常闇トワ", "星街すいせい"]

[[videos]]
url = "https://www.youtube.com/watch?v=ugTie-8HXLw"

[[videos]]
url = "https://www.youtube.com/watch?v=BYTP2oLr59Q"

[[videos]]
url = "https://www.youtube.com/watch?v=16WxRVoTAx0"
