tags = ["桃鈴ねね"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLet0wKVboCzEMtX-hZQn1obu40HWVKn7q"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLet0wKVboCzF7QGobE077uQ6HogY8abWM"
tags = ["オリジナル"]
