tags = ["紫咲シオン"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLzYaEBSRCCt5kgnBdQkLM7yDDZt2_NIZG"

[[videos]]
url = "https://www.youtube.com/watch?v=pMNnZIz6YYM"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=SoSuMVviNaU"
tags = ["湊あくあ", "紫咲シオン"]
