tags = ["夏色まつり"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PL6sZ3uYmeG1vGZVLNlWdJkm3W0R86y_Qa"

[[videos]]
url = "https://www.youtube.com/watch?v=-ivI-Vb920I"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=llv_1-WEQGg"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=Lhu7zb1hers"
tags = ["白上フブキ", "さくらみこ", "宝鐘マリン"]

[[videos]]
url = "https://www.youtube.com/watch?v=x1BGG98tcrg"
tags = ["大神ミオ", "不知火フレア", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=trKQ_PG4Z98"
tags = ["大空スバル", "さくらみこ", "白銀ノエル", "宝鐘マリン", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=kUxl0rkmD08"
tags = ["百鬼あやめ"]

[[videos]]
url = "https://www.youtube.com/watch?v=z2pWWKSPofA"
tags = ["紫咲シオン"]

[[videos]]
url = "https://www.youtube.com/watch?v=_J8vpBOciBw"
tags = [
  "星街すいせい",
  "不知火フレア",
  "桃鈴ねね",
]
