tags = ["尾丸ポルカ"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLWGY2acU-ZeTnH4EvPHYEcqCUx145dDUP"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLWGY2acU-ZeTOrh2XBRzA02UzTR-pWDlG"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=mFLu8TKDsrk"
tags = ["さくらみこ", "不知火フレア", "角巻わため", "常闇トワ", "湊あくあ"]
