tags = ["大空スバル"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLOLvMgy3Jf3FVLGFJ4HooifOvd3UIQ1eJ"

[[videos]]
url = "https://www.youtube.com/watch?v=RRsw5tT8BJI"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=bbYReCtSBbk"

ignores = [
  # ライブ
  "https://www.youtube.com/watch?v=mhvHZpK-9Ss",
  "https://www.youtube.com/watch?v=n6yep2gl1HY"
]
