tags = ["ロボ子さん"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLF54qiUa9cTu9eyx3Ukx88jtJUCKGFvWL"

[[videos]]
url = "https://www.youtube.com/watch?v=K8n-pGOrpzc"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=UXuMSLOUhgs"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=5A_RqpENxvg"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=yfEUPlRuPac"
tags = ["友人A"]

[[videos]]
url = "https://www.youtube.com/watch?v=ZshLem1OV7k"

[[videos]]
url = "https://www.youtube.com/watch?v=RJwpJIe5FmY"

[[videos]]
url = "https://www.youtube.com/watch?v=sJZoMJfIpmA"

[[videos]]
url = "https://www.youtube.com/watch?v=ydprczRfM48"

[[videos]]
url = "https://www.youtube.com/watch?v=yIvcKk4vZ7Y"
tags = ["さくらみこ", "大神ミオ"]

[[videos]]
url = "https://www.youtube.com/watch?v=c25iBKPN6w4"

[[videos]]
url = "https://www.youtube.com/watch?v=K7FqZJS-ZwA"
tags = ["ときのそら"]

[[videos]]
url = "https://www.youtube.com/watch?v=fY1CQ5kSRxY"

[[videos]]
url = "https://www.youtube.com/watch?v=e_EqIA6ZWqs"

[[videos]]
url = "https://www.youtube.com/watch?v=QP-caiSnm2Q"
tags = ["アキ・ローゼンタール"]

[[videos]]
url = "https://www.youtube.com/watch?v=ETckHHfH7EI"

[[videos]]
url = "https://www.youtube.com/watch?v=6sHk3CYD-IA"
tags = ["アキ・ローゼンタール", "百鬼あやめ", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=UYyzAlbcw8w"
tags = [
  "夜空メル",
  "アキ・ローゼンタール",
  "夏色まつり",
  "湊あくあ",
  "大神ミオ",
  "さくらみこ",
  "不知火フレア",
  "常闇トワ",
  "オリジナル"
]

[[videos]]
url = "https://www.youtube.com/watch?v=Ciq_CDwmICU"
tags = [
  "夜空メル",
  "アキ・ローゼンタール",
  "湊あくあ",
  "不知火フレア",
  "オリジナル"
]

[[videos]]
url = "https://www.youtube.com/watch?v=ue7mFSgBAH0"
tags = ["アキ・ローゼンタール", "姫森ルーナ"]
