tags = ["沙花叉クロヱ"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLi6TWx3pTf1fVyYNxUCKNHmmssZjKnK9K"
tags = ["オリジナル"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLi6TWx3pTf1dHW-DvMpPEW2NLDICBkW8z"
