tags = ["不知火フレア"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLBoFNGFmekcMIhlW5Z-umsS3VPnQx7tI8"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLBoFNGFmekcMx0GWBvp69cXileGC--Ku-"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=YVdA-QCcXYc"
tags = ["白銀ノエル"]
