tags = ["獅白ぼたん"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLrQwEkvx5phi8umsHZd-VKAKZ1XZ_7OCy"

[[videos]]
url = "https://www.youtube.com/watch?v=npVP58NvdQ8"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=kBfXjNFo3Mo"
tags = ["オリジナル"]
