tags = ["鷹嶺ルイ"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLD992QYJ2953ekTB3YuoHcF505PWPXlwb"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLD992QYJ2953VAH1hnegHhcATpRr2w_0A"
tags = ["オリジナル"]
