tags = ["常闇トワ"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLIHyIgRAWkUz3MAUPbTg9XcuP_rzDJ1bk"

[[videos]]
url = "https://www.youtube.com/watch?v=Ud73fm4Uoq0"
tags = ["常闇トワ", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=Zc05le75CfI"
tags = ["常闇トワ", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=D8pdSRs_C4o"
tags = ["常闇トワ", "さくらみこ", "アキ・ローゼンタール", "尾丸ポルカ", "風真いろは"]
