tags = ["角巻わため"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLZ34fLWik_iAP2AdGLOHthUhAJTrEXqGb"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLZ34fLWik_iBK39rTWRAs_G93pnUW3K-7"
tags = ["オリジナル"]

# [[videos]]
# url = "https://www.youtube.com/watch?v=-EHqt_WtpGA"
# tags = ["オリジナル"]
