tags = ["雪花ラミィ"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PL7Mw3OdFU891DfLqncG9cbkwH80lHFZEl"

[[videos]]
url = "https://www.youtube.com/watch?v=ULtGHb83pTI"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=kU-KWiNpRmw"
tags = ["オリジナル"]
