
tags = ["癒月ちょこ"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLbk25bH74T5ZgCqaphR7q_dQ8Ja65Z4r_"

[[videos]]
url = "https://www.youtube.com/watch?v=njeUgc0a5ko"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=jlELf83gpBw"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=QaEW5hhLxuk"
tags = ["夜空メル", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=BAx2GtYGJxs"
tags = ["大空スバル", "姫森ルーナ"]

[[videos]]
url = "https://www.youtube.com/watch?v=MQ-QnXZR4mc"
tags = ["大空スバル", "姫森ルーナ"]
