tags = ["Airani Iofifteen"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PL0OWyC-pOgQnQ1POfg1fOiXffUPE-b3sR"

[[videos]]
url = "https://www.youtube.com/watch?v=MJz6SHKmrC4"
tags = ["オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=Rd6kufQ7ONc"
tags = ["オリジナル"]
