tags = ["Kobo Kanaeru"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLwtTNsTyL23S4MNl0-gdozd769CytE_9X"

[[videos]]
url = "https://www.youtube.com/watch?v=SF-_47-oCtk"
tags = ["オリジナル"]
