tags = ["Pavolia Reine"]

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLrALGrrF-6IVnnurSv7Nxdxpo5zJmmjnC"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PLrALGrrF-6IWBHB3pdou530lFKrSsCtD4"
tags = ["オリジナル"]
