files = [
  # 0th gen
  "jp/azki.toml",
  "jp/tokino-sora.toml",
  "jp/robocosan.toml",
  "jp/sakura-miko.toml",
  "jp/hoshimachi-suisei.toml",
  # 1st gen
  "jp/akai-haato.toml",
  "jp/aki-rosenthal.toml",
  "jp/natsuiro-matsuri.toml",
  "jp/shirakami-fubuki.toml",
  "jp/yozora-mel.toml",
  # 2nd gen
  "jp/oozora-subaru.toml",
  "jp/minato-aqua.toml",
  "jp/yuzuki-choco.toml",
  "jp/nakiri-ayame.toml",
  "jp/murasaki-shion.toml",
  # gamers
  "jp/ookami-mio.toml",
  "jp/nekomata-okayu.toml",
  "jp/inugami-korone.toml",
  # 3rd gen
  "jp/usada-pekora.toml",
  "jp/shiranui-flare.toml",
  "jp/shirogane-noel.toml",
  "jp/houshou-marine.toml",
  # 4th gen
  "jp/amane-kanata.toml",
  "jp/tsunomaki-watame.toml",
  "jp/tokoyami-towa.toml",
  "jp/himemori-luna.toml",
  "jp/kiryu-coco.toml",
  # 5th gen
  "jp/yukihana-lamy.toml",
  "jp/momosuzu-nene.toml",
  "jp/shishiro-botan.toml",
  "jp/omaru-polka.toml",
  # holox
  "jp/laplus-darkness.toml",
  "jp/takane-lui.toml",
  "jp/hakui-koyori.toml",
  "jp/sakamata-chloe.toml",
  "jp/kazama-iroha.toml"
]

[[videos]]
url = "https://www.youtube.com/watch?v=O-SXhtYjprc"
tags = [
  "ときのそら",
  "ロボ子さん",
  "夜空メル",
  "アキ・ローゼンタール",
  "赤井はあと",
  "白上フブキ",
  "夏色まつり",
  "湊あくあ",
  "紫咲シオン",
  "百鬼あやめ",
  "癒月ちょこ",
  "大空スバル",
  "大神ミオ",
  "さくらみこ",
  "猫又おかゆ",
  "戌神ころね",
  "兎田ぺこら",
  "潤羽るしあ",
  "宝鐘マリン",
  "不知火フレア",
  "白銀ノエル"
]

[[videos]]
url = "https://www.youtube.com/watch?v=68KV7JnrvDo"
tags = [
  "ときのそら",
  "ロボ子さん",
  "夜空メル",
  "アキ・ローゼンタール",
  "赤井はあと",
  "白上フブキ",
  "夏色まつり",
  "湊あくあ",
  "紫咲シオン",
  "百鬼あやめ",
  "癒月ちょこ",
  "大空スバル",
  "AZKi",
  "大神ミオ",
  "さくらみこ",
  "猫又おかゆ",
  "戌神ころね",
  "兎田ぺこら",
  "潤羽るしあ",
  "宝鐘マリン",
  "不知火フレア",
  "白銀ノエル",
  "星街すいせい",
  "オリジナル"
]

[[videos]]
url = "https://www.youtube.com/watch?v=RrsGNMMghKM"
tags = [
  "ときのそら",
  "ロボ子さん",
  "夜空メル",
  "アキ・ローゼンタール",
  "赤井はあと",
  "白上フブキ",
  "夏色まつり",
  "湊あくあ",
  "紫咲シオン",
  "百鬼あやめ",
  "癒月ちょこ",
  "大空スバル",
  "AZKi",
  "大神ミオ",
  "さくらみこ",
  "猫又おかゆ",
  "戌神ころね",
  "オリジナル"
]

[[videos]]
url = "https://www.youtube.com/watch?v=0p7P9XRoeEo"
tags = ["夜空メル", "紫咲シオン", "白銀ノエル", "宝鐘マリン"]

[[videos]]
url = "https://www.youtube.com/watch?v=OpveB76DTZk"
tags = ["BABACORN", "白上フブキ", "宝鐘マリン", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=AvOu9B5rsdA"
tags = [
  "いろはにほへっと あやふぶみ",
  "白上フブキ",
  "百鬼あやめ",
  "大神ミオ",
  "オリジナル"
]

[[videos]]
url = "https://www.youtube.com/watch?v=5ArDbvfds9k"
tags = ["ORIO", "天音かなた", "常闇トワ", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=23nEnPOXLEk"
tags = ["ORIO", "天音かなた", "常闇トワ", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=4Hg0Nchl3HU"
tags = [
  "白上フブキ",
  "百鬼あやめ",
  "大神ミオ",
  "いろはにほへっと あやふぶみ",
  "オリジナル"
]

[[videos]]
url = "https://www.youtube.com/watch?v=UAMhYU9SHzo"
tags = ["AZKi", "ときのそら", "夏色まつり"]

[[videos]]
url = "https://www.youtube.com/watch?v=gDfd2ICWezg"
tags = [
  "天音かなた",
  "尾丸ポルカ",
  "獅白ぼたん",
  "不知火フレア",
  "星街すいせい",
  "桃鈴ねね",
  "雪花ラミィ"
]

[[videos]]
url = "https://www.youtube.com/watch?v=Hye06iM9640"
tags = ["不知火フレア", "天音かなた", "常闇トワ", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=3QJD9iekpDQ"
tags = ["スパイスラブ", "大空スバル", "湊あくあ", "兎田ぺこら"]

[[videos]]
url = "https://www.youtube.com/watch?v=Mb2oMO-SK7w"
tags = ["ロボ子さん", "白上フブキ"]

[[videos]]
url = "https://www.youtube.com/watch?v=MKEb-Ox1KEw"
tags = ["宝鐘マリン", "Gawr Gura", "湊あくあ", "Ninomae Ina'nis", "オリジナル"]

# 1期生
[[videos]]
url = "https://www.youtube.com/watch?v=VCJTJX1kXe4"
tags = ["白上フブキ", "夜空メル", "アキ・ローゼンタール", "赤井はあと", "夏色まつり", "オリジナル"]

[[videos]]
url = "https://www.youtube.com/watch?v=mE_Q5vam910"
tags = ["白上フブキ", "夜空メル", "アキ・ローゼンタール", "赤井はあと", "夏色まつり", "オリジナル"]

# 3期生
[[video]] # https://www.youtube.com/watch?v=F61eDAXtmnw
id = "F61eDAXtmnw"
tags = ["オリジナル", "不知火フレア", "宝鐘マリン", "兎田ぺこら", "潤羽るしあ", "白銀ノエル"]

# 4期生
[[video]] # https://www.youtube.com/watch?v=k7cpjmkc1Rw
id = "k7cpjmkc1Rw"
tags = ["天音かなた", "桐生ココ", "角巻わため", "常闇トワ", "姫森ルーナ", "オリジナル"]
