files = ["jp.toml", "en.toml", "id.toml"]

# fallback
[[playlists]]
url = "https://www.youtube.com/playlist?list=PL1NeGg1woXqlISJkxjgwHKgB8LmR7tk92"

[[playlists]]
url = "https://www.youtube.com/playlist?list=PL1NeGg1woXqkTks79_kSoxBrEKloB9SrI"
tags = ["オリジナル"]
# [[video]]
# hololive - 過去の大型ライブの映像セレクション(非公開)
# id = "GIZPAJHW5bk"
# tags = ["official", "ライブ"]
ignores = [
  # https://www.hololive.tv/terms
  # 音楽利用に関するガイドラインの対象外となる楽曲について
  # hololive IDOL PROJECT／キラメキライダー☆
  "https://www.youtube.com/watch?v=0o3VrBLh8jI",
  "https://www.youtube.com/watch?v=rDSIUPkuM7U",
]
