name: GitHub Pages

on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 1 * * *
  # push:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Build SvelteKit
        run: pnpm build
        env:
          VITE_API_KEY: ${{ secrets.API_KEY }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
