name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/firebase-cli
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOLOLIVE_MUSIC }}
      - uses: ./.github/actions/get-pr-id
        id: pr-id
      - run: pnpm build
      - run: firebase hosting:channel:deploy ${{ steps.pr-id.outputs.pr-id }}
  delete_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/firebase-cli
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOLOLIVE_MUSIC }}
      - uses: ./.github/actions/get-pr-id
        id: pr-id
      - run: firebase hosting:channel:delete -f ${{ steps.pr-id.outputs.pr-id }}
